{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.5.1.jar",
          "url": "aaptcompiler-8.5.1.jar",
          "size": 499315,
          "sha512": "f2c0794dc36fbc67925f82ee6096a41bcf9fcec3917afdcf81cefa9a5fb92e9b1b8f2866124896b649d151090b259127453a6f651619becb0dc004b88d78de59",
          "sha256": "670a3902165cf2033b90e64a4dbed8483809a2cae7d5bedcace3830960c176fd",
          "sha1": "0665c2b4c5313877933d3e1ac98ff8711839cfc9",
          "md5": "1b16f26c3a17a43e0fbdec4109e54494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.5.1-11315950"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.5.1.jar",
          "url": "aaptcompiler-8.5.1.jar",
          "size": 499315,
          "sha512": "f2c0794dc36fbc67925f82ee6096a41bcf9fcec3917afdcf81cefa9a5fb92e9b1b8f2866124896b649d151090b259127453a6f651619becb0dc004b88d78de59",
          "sha256": "670a3902165cf2033b90e64a4dbed8483809a2cae7d5bedcace3830960c176fd",
          "sha1": "0665c2b4c5313877933d3e1ac98ff8711839cfc9",
          "md5": "1b16f26c3a17a43e0fbdec4109e54494"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.5.1-javadoc.jar",
          "url": "aaptcompiler-8.5.1-javadoc.jar",
          "size": 81065,
          "sha512": "97cb21f3aa24941d95a0fda031ee47ac75cf5527408350f4290b23f30a0ceb5ccd997f9ec5769791bff58414cba7e14c8fad74513904f3b5e0a4d9881ab1aa59",
          "sha256": "0aeb1d43b4318ce0ac0eb46c687930cb3808a270e1fa6545d4a081808ad96ea3",
          "sha1": "60d8b3eae084a4b19cf16e86198b23f0bbd000ee",
          "md5": "c4cf67b2c110fca75868dbb369f41c37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.5.1-sources.jar",
          "url": "aaptcompiler-8.5.1-sources.jar",
          "size": 152981,
          "sha512": "61d7c8d3acf151120f7c98ea8687c1192db5e84e989e35fa9161079b7396230673f6b86575ab9c46dd7e7848d410d8b2521bcd520c2a933cb51f182595babe6a",
          "sha256": "ca52af55ba474e02fd9cd03a0230b09501c8d991de4d445f0cf244bc196e00f7",
          "sha1": "185b7d63e8ca1222b0a7e65cde54abf7f545b653",
          "md5": "81187e8a1fa9ca2b8eaf0c2c2a7b2e0f"
        }
      ]
    }
  ]
}
