{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.5.1.jar",
          "url": "gradle-api-8.5.1.jar",
          "size": 340460,
          "sha512": "e722f03c634e0bd11ab3d02cb79142dbdabfcc7df044473900e1b27020ab5d8af872a52525418a6ba0f527455a6648e98556411b791709732654722666e1ac3a",
          "sha256": "8fdf516c334e0a2951e441c5d4aa039644bfeef69ecbcb80a12026cc430049e9",
          "sha1": "f30c56651bc6e0c81cdc33aadc9edbbe6d617c18",
          "md5": "128c52357d95a72781ade772a4d880c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.5.1.jar",
          "url": "gradle-api-8.5.1.jar",
          "size": 340460,
          "sha512": "e722f03c634e0bd11ab3d02cb79142dbdabfcc7df044473900e1b27020ab5d8af872a52525418a6ba0f527455a6648e98556411b791709732654722666e1ac3a",
          "sha256": "8fdf516c334e0a2951e441c5d4aa039644bfeef69ecbcb80a12026cc430049e9",
          "sha1": "f30c56651bc6e0c81cdc33aadc9edbbe6d617c18",
          "md5": "128c52357d95a72781ade772a4d880c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.5.1-javadoc.jar",
          "url": "gradle-api-8.5.1-javadoc.jar",
          "size": 151132,
          "sha512": "4e0e0d87254bf8af771ce201a0f30c51e7bcc264fcbd0fedeae58d27e8ccde10f1f84f4ab7cd7ff99b7ba81e5a0221419fcdcb4aa54ddb9c87236613ca3582f4",
          "sha256": "fe77028044e7c0053cb21167b62edbfd723dcb27f0fdd62724b07233aa3c74fd",
          "sha1": "71b6a254f391069a6604b42c44c2141e4b06e75b",
          "md5": "45d68fb4d2e617e0d72d02a6632dfc3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.5.1-sources.jar",
          "url": "gradle-api-8.5.1-sources.jar",
          "size": 344806,
          "sha512": "b59c15c5d49207d4a0fd0640ca2bce1af8900077570b238ec645724d44fa37217132378cf15dde0fecfd357bc10d6b74d49ec262591b1ca50cd4443e0c1e73b0",
          "sha256": "c27bbc047dbe4ef825084d67d53c72f1c334a43329a927981f0b21062ad456d6",
          "sha1": "03813a94d42e60b4acb5d06c5f8b4bb572e5379b",
          "md5": "92ec9b9e7a798fe7a9d7a95fc82efd68"
        }
      ]
    }
  ]
}
