name: scanna
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  google_fonts: ^2.3.2
  awesome_dialog: ^3.1.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.8.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^5.1.0
  validators: ^3.0.0
  fluttertoast: ^8.2.6
  provider: ^6.0.3
  local_auth: ^2.1.7
  firebase_database: ^10.0.12
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf


l10n:
  path: l10n
