name: scanna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  awesome_dialog: ^3.2.1
  modal_progress_hud_nsn: ^0.5.1

  # Firebase (Latest compatible versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_auth_web: ^5.13.2
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_storage: ^12.4.5

  # Authentication & Social Login (Updated versions)
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.2.1
  local_auth: ^2.3.0

  # State Management & Storage
  provider: ^6.1.2
  shared_preferences: ^2.3.3

  # Validation & Utils (Updated versions)
  validators: ^3.0.0
  fluttertoast: ^8.2.8
  intl: ^0.20.2
  syncfusion_flutter_pdfviewer: ^30.1.40

  # Notifications (Updated)
  flutter_local_notifications: ^19.3.1

  # Scanning & QR Codes (Updated versions)
  mobile_scanner: ^7.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  barcode: ^2.2.8
  barcode_widget: ^2.0.3

  # File & PDF Operations (Updated versions)
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.4
  open_file: ^3.5.7
  http: ^1.4.0

  # Permissions & Lifecycle (Updated versions)
  permission_handler: ^12.0.1
  flutter_plugin_android_lifecycle: ^2.0.22

  # Cross-platform compatibility
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  # Fonts section removed - using google_fonts package instead
  # This eliminates font file errors and provides better performance

flutter_intl:
  enabled: true

l10n:
  path: l10n