{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.5.1.jar",
          "url": "builder-8.5.1.jar",
          "size": 14159152,
          "sha512": "d09c53ada776852384d15d91c8ce8f0f60d0094fa0d89af3f905b793a01b473ec99774e3575a6e01e8497991f89dc05db003ea2406be7086087ca744fa0846f5",
          "sha256": "55e1bd314b6b411f257ebc9551912db68bfe0137147193f84a32c7890ff1d7c2",
          "sha1": "750409c265fc23845223f47ed78da47548b3cd3a",
          "md5": "c43ef1dac0905a6032fcdf67dcebf111"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.5.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.5.1.jar",
          "url": "builder-8.5.1.jar",
          "size": 14159152,
          "sha512": "d09c53ada776852384d15d91c8ce8f0f60d0094fa0d89af3f905b793a01b473ec99774e3575a6e01e8497991f89dc05db003ea2406be7086087ca744fa0846f5",
          "sha256": "55e1bd314b6b411f257ebc9551912db68bfe0137147193f84a32c7890ff1d7c2",
          "sha1": "750409c265fc23845223f47ed78da47548b3cd3a",
          "md5": "c43ef1dac0905a6032fcdf67dcebf111"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.5.1-javadoc.jar",
          "url": "builder-8.5.1-javadoc.jar",
          "size": 397693,
          "sha512": "52ddc7160091324035cc817556f3035ec45e7c06a270a91f2e75810e92454e8285f43189a7234ff278c56a95e7cbd3abc49cb4e0b1c9bb949ac23164b213f056",
          "sha256": "46d8d914b6ee2660ecc47bff2e3f20680ec92aff1d674489b49a2c31bb4955c7",
          "sha1": "0c4ed60d0d33c9920d52b1b27d34f52bb9e8ccd9",
          "md5": "2006c722881554a83a6c96e0faeea180"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.5.1-sources.jar",
          "url": "builder-8.5.1-sources.jar",
          "size": 280881,
          "sha512": "c8a78f836861cd1ccf26d389dab00e048d7829a72f60c27e2c03797a3dd3f6725d1b80351bd7fc9557d78e9b5a6c6df209ef954806da0a28b6166f9cc82d57d8",
          "sha256": "49bdc33475568c6a04d2aa03bf799aff40a6d41ca72319994d3ff73559c3997c",
          "sha1": "39c9561eb56aa5eed756342b5661af6f2b491549",
          "md5": "3ea58c902bcd8f85e21de8edd5522be7"
        }
      ]
    }
  ]
}
