{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.kotlin",
    "module": "gradle-kotlin-dsl-plugins",
    "version": "5.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11-20240930074649+0000"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-kotlin-dsl-plugins-5.1.2.jar",
          "url": "gradle-kotlin-dsl-plugins-5.1.2.jar",
          "size": 46523,
          "sha512": "b451f0ef95508208518ef90067ff414b4e8f6db2436f9afa23e799fafa7b3d048478fcd30cc6401046ed562fb305eab996452ccd1a77cd81362a81e91fd43840",
          "sha256": "b58c3e5c35a00259fd402debf3da47aa3ad085c3f4be72f902ea1261b35019ae",
          "sha1": "a80ee107fa8d59ec7418694bf7e6f90567956ee8",
          "md5": "a03d5de0b3423ddbc935f1f4eefc9a6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-sam-with-receiver",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-assignment",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-kotlin-dsl-plugins-5.1.2.jar",
          "url": "gradle-kotlin-dsl-plugins-5.1.2.jar",
          "size": 46523,
          "sha512": "b451f0ef95508208518ef90067ff414b4e8f6db2436f9afa23e799fafa7b3d048478fcd30cc6401046ed562fb305eab996452ccd1a77cd81362a81e91fd43840",
          "sha256": "b58c3e5c35a00259fd402debf3da47aa3ad085c3f4be72f902ea1261b35019ae",
          "sha1": "a80ee107fa8d59ec7418694bf7e6f90567956ee8",
          "md5": "a03d5de0b3423ddbc935f1f4eefc9a6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-kotlin-dsl-plugins-5.1.2-sources.jar",
          "url": "gradle-kotlin-dsl-plugins-5.1.2-sources.jar",
          "size": 10497,
          "sha512": "8e69a6780e2057e4a62ad1cd4349fa0eb5da8dbbf72e1253e2191b1a2f2fa88b16957e8d30170ad02cddce4c4c91f2246e8220f9b4e55b53aa65924ff35f4f5c",
          "sha256": "ba97cf990be95deb7ccde7d07643d0bf4d98bad81adf6e5f0cac100946e94b14",
          "sha1": "b6810f1983371d5a425815315c3018443dab8391",
          "md5": "f8a0c6769609e5d414862a0d65c4dc09"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-kotlin-dsl-plugins-5.1.2-javadoc.jar",
          "url": "gradle-kotlin-dsl-plugins-5.1.2-javadoc.jar",
          "size": 298,
          "sha512": "aa92711c1c12385dae4c88c8681345101cdfbf008ecc61483f285928b32754b9b32d7c6378634d70c71a70526c508b8dd3b88452648e0d7e7ede4ffd3193807e",
          "sha256": "49718667bdeb5af10b60fbc217016d81bcf6956c8cde17681a0f5ab4db07b602",
          "sha1": "21be3a7f1031ce03d78e5e44bab4cc1683b606a1",
          "md5": "f6eb7695391ed1b298dd493f8477c06d"
        }
      ]
    }
  ]
}
