{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-sam-with-receiver",
    "version": "2.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21.jar",
          "url": "kotlin-sam-with-receiver-2.0.21.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21.jar",
          "url": "kotlin-sam-with-receiver-2.0.21.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle70-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle70-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle70-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle70-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle70.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle70.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle70.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle70.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle71JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle71-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle71-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle71SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle71-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle71-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle71ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle71.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle71.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle71RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle71.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle71.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle74JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle74-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle74-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle74SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle74-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle74-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle74ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle74"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle74.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle74.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle74RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle74"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle74.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle74.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle75JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle75-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle75-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle75SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle75-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle75-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle75ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle75"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle75.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle75.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle75RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle75"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle75.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle75.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle76JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle76-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle76-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle76SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle76-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle76-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle76ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle76"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle76.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle76.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle76RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle76"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle76.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle76.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle80-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle80-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle80-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle80-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle80.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle80.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle80.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle80.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle81-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle81-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle81-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle81-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle81.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle81.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle81.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle81.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle82-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle82-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle82-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle82-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle82.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle82.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle82.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle82.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle85JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle85-javadoc.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle85-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle85-sources.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle85-sources.jar",
          "size": 5533,
          "sha512": "6ea8f099cbf8e2112fdd5a36c941981d9d16f5d748013caf830244402930d5c063732d19f3628f54c1b028bc7b493ca8adfe78af93e1f40bec4fdd15e3c35da7",
          "sha256": "60c18ba69669323c2b2c778849293d1a7241eb2cb74c12b5b36ac5624ef2e294",
          "sha1": "8b5b0262aa923e3df67ad8056077c327603a99ff",
          "md5": "fd89081769ad0e1bd87a4b40b7bdd4cb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle85.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle85.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-sam-with-receiver-2.0.21-gradle85.jar",
          "url": "kotlin-sam-with-receiver-2.0.21-gradle85.jar",
          "size": 14934,
          "sha512": "8bcc7fcb1fc40a9575e310904a15348fbc524b99d32f6b64604865771455f64427f44f72ef25d7467a796bc17b803f5bed42bbf883a7cfe0941bdb82dfa2ab78",
          "sha256": "1d236e362233b9a271e50b223a50c8dbeadd0350b63a2464608256852da368a3",
          "sha1": "09a5580a59ebfacd6e355accb87a63e05c45516f",
          "md5": "9c3945d3657ac1330af0cf0f525781e6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-sam-with-receiver",
          "version": "2.0.21"
        }
      ]
    }
  ]
}
