// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0nxVZy9v-Ook6Cqwvw9xYkIj-6By1DY',
    appId: '1:977889421305:web:83b1eca3340e17febdbf28',
    messagingSenderId: '977889421305',
    projectId: 'gradescanna-935d8',
    authDomain: 'gradescanna-935d8.firebaseapp.com',
    databaseURL: 'https://gradescanna-935d8-default-rtdb.firebaseio.com',
    storageBucket: 'gradescanna-935d8.appspot.com',
    measurementId: 'G-J9V1NCZ74X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27P01u4DeKlk4UxaDmdFwN26fJEWYhNY',
    appId: '1:977889421305:android:a74dbcfca71d7f50bdbf28',
    messagingSenderId: '977889421305',
    projectId: 'gradescanna-935d8',
    databaseURL: 'https://gradescanna-935d8-default-rtdb.firebaseio.com',
    storageBucket: 'gradescanna-935d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGgaUkTkA5IVAeJMT3s7vI9D4Ut8jdQeI',
    appId: '1:977889421305:ios:e0a8246fc7aa937abdbf28',
    messagingSenderId: '977889421305',
    projectId: 'gradescanna-935d8',
    databaseURL: 'https://gradescanna-935d8-default-rtdb.firebaseio.com',
    storageBucket: 'gradescanna-935d8.appspot.com',
    iosClientId: '977889421305-gmq6t5qre0g6vi6d4453i9p2b87k6fk2.apps.googleusercontent.com',
    iosBundleId: 'com.deliciafernandes.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGgaUkTkA5IVAeJMT3s7vI9D4Ut8jdQeI',
    appId: '1:977889421305:ios:a44b86ae9ddae7e6bdbf28',
    messagingSenderId: '977889421305',
    projectId: 'gradescanna-935d8',
    databaseURL: 'https://gradescanna-935d8-default-rtdb.firebaseio.com',
    storageBucket: 'gradescanna-935d8.appspot.com',
    iosClientId: '977889421305-puid2qgg7av3c2egnej2n3os5f25cstj.apps.googleusercontent.com',
    iosBundleId: 'com.deliciafernandes.scanna3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ0nxVZy9v-Ook6Cqwvw9xYkIj-6By1DY',
    appId: '1:977889421305:web:00e3281fb9da5c09bdbf28',
    messagingSenderId: '977889421305',
    projectId: 'gradescanna-935d8',
    authDomain: 'gradescanna-935d8.firebaseapp.com',
    databaseURL: 'https://gradescanna-935d8-default-rtdb.firebaseio.com',
    storageBucket: 'gradescanna-935d8.appspot.com',
    measurementId: 'G-0KHK775HL3',
  );
}
