// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOjIEXYxYDu-efZm9w17MorKetK8ZWyM',
    appId: '1:531504318019:web:ed2c566f021fba98f476f6',
    messagingSenderId: '531504318019',
    projectId: 'teachandlearn-d3be7',
    authDomain: 'teachandlearn-d3be7.firebaseapp.com',
    databaseURL: 'https://teachandlearn-d3be7-default-rtdb.firebaseio.com',
    storageBucket: 'teachandlearn-d3be7.appspot.com',
    measurementId: 'G-94G3JJ844C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6lC-adPRfMPj3tnpMMvmQZUFaOQzOqA4',
    appId: '1:531504318019:android:a8296d6c98e3f327f476f6',
    messagingSenderId: '531504318019',
    projectId: 'teachandlearn-d3be7',
    databaseURL: 'https://teachandlearn-d3be7-default-rtdb.firebaseio.com',
    storageBucket: 'teachandlearn-d3be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFEmNMe2GhJBbtjI4ViLqESlC3Lonb3gA',
    appId: '1:531504318019:ios:1c4237806589001ef476f6',
    messagingSenderId: '531504318019',
    projectId: 'teachandlearn-d3be7',
    databaseURL: 'https://teachandlearn-d3be7-default-rtdb.firebaseio.com',
    storageBucket: 'teachandlearn-d3be7.appspot.com',
    androidClientId: '531504318019-3rek4jhom9jubc1ou8fqr43u4ehavsdv.apps.googleusercontent.com',
    iosClientId: '531504318019-6bqhl2t6trtom8ihv6qa724bl8e78f57.apps.googleusercontent.com',
    iosBundleId: 'com.deliciafernandes.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFEmNMe2GhJBbtjI4ViLqESlC3Lonb3gA',
    appId: '1:531504318019:ios:6a974aaa440c6df6f476f6',
    messagingSenderId: '531504318019',
    projectId: 'teachandlearn-d3be7',
    databaseURL: 'https://teachandlearn-d3be7-default-rtdb.firebaseio.com',
    storageBucket: 'teachandlearn-d3be7.appspot.com',
    androidClientId: '531504318019-3rek4jhom9jubc1ou8fqr43u4ehavsdv.apps.googleusercontent.com',
    iosClientId: '531504318019-tacqa4sepakv8a88q95e9g3714o9u8tf.apps.googleusercontent.com',
    iosBundleId: 'com.deliciafernandes.scanna3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSOjIEXYxYDu-efZm9w17MorKetK8ZWyM',
    appId: '1:531504318019:web:022388aeb1886488f476f6',
    messagingSenderId: '531504318019',
    projectId: 'teachandlearn-d3be7',
    authDomain: 'teachandlearn-d3be7.firebaseapp.com',
    databaseURL: 'https://teachandlearn-d3be7-default-rtdb.firebaseio.com',
    storageBucket: 'teachandlearn-d3be7.appspot.com',
    measurementId: 'G-P4QQ1HE31G',
  );

}